services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./logs:/usr/src/app/logs

