services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

