import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  Button,
  Grid,
  Card,
  CardContent,
  TextField,
  Paper,
  Chip,
  Alert,
  CircularProgress,
  Stack,
  Divider,
  IconButton,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
} from '@mui/material';
import {
  AutoAwesome,
  Psychology,
  Send,
  ContentCopy,
  Refresh,
  Star,
  Schedule,
  Analytics,
  Security,
  Speed,
  CheckCircle,
  Lightbulb,
  TrendingUp,
  People,
  Business,
  School,
  Work,
  Public,
  Close,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';

const AIGeneration = () => {
  const navigate = useNavigate();
  const [prompt, setPrompt] = useState('');
  const [generatedContent, setGeneratedContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState(null);

  const templates = [
    {
      id: 'professional',
      title: 'Professional Insight',
      description: 'Share industry insights and professional experiences',
      icon: <Business sx={{ fontSize: 30, color: '#0077B5' }} />,
      prompt: 'Write a professional LinkedIn post about industry insights and best practices.',
    },
    {
      id: 'personal',
      title: 'Personal Story',
      description: 'Share personal experiences and lessons learned',
      icon: <People sx={{ fontSize: 30, color: '#00A3E0' }} />,
      prompt: 'Write a personal LinkedIn post sharing a meaningful experience and key takeaways.',
    },
    {
      id: 'educational',
      title: 'Educational Content',
      description: 'Share knowledge and teach your network',
      icon: <School sx={{ fontSize: 30, color: '#28A745' }} />,
      prompt: 'Write an educational LinkedIn post that teaches something valuable to your network.',
    },
    {
      id: 'career',
      title: 'Career Growth',
      description: 'Discuss career development and opportunities',
      icon: <Work sx={{ fontSize: 30, color: '#6F42C1' }} />,
      prompt: 'Write a LinkedIn post about career development and professional growth.',
    },
    {
      id: 'industry',
      title: 'Industry Trends',
      description: 'Comment on industry trends and developments',
      icon: <TrendingUp sx={{ fontSize: 30, color: '#E91E63' }} />,
      prompt: 'Write a LinkedIn post discussing current industry trends and their impact.',
    },
    {
      id: 'thought-leadership',
      title: 'Thought Leadership',
      description: 'Share original ideas and perspectives',
      icon: <Lightbulb sx={{ fontSize: 30, color: '#FFD700' }} />,
      prompt: 'Write a thought leadership LinkedIn post with original insights and perspectives.',
    },
  ];

  const features = [
    {
      icon: <Psychology sx={{ fontSize: 40, color: '#0077B5' }} />,
      title: 'AI-Powered Generation',
      description: 'Advanced Gemini AI creates engaging, professional content tailored to your industry.',
    },
    {
      icon: <Speed sx={{ fontSize: 40, color: '#00A3E0' }} />,
      title: 'Lightning Fast',
      description: 'Generate high-quality content in seconds, not hours.',
    },
    {
      icon: <Analytics sx={{ fontSize: 40, color: '#28A745' }} />,
      title: 'Optimized for Engagement',
      description: 'Content designed to maximize likes, comments, and shares.',
    },
    {
      icon: <Security sx={{ fontSize: 40, color: '#6F42C1' }} />,
      title: 'Professional Tone',
      description: 'Maintains your professional brand while being engaging.',
    },
  ];

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt or select a template');
      return;
    }

    setLoading(true);
    setError('');
    setSuccess('');

    try {
      // Simulate AI generation (replace with actual API call)
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const generatedText = `Based on your prompt "${prompt}", here's a professional LinkedIn post:

🚀 Just had an incredible breakthrough in my professional journey that I had to share with my network!

The key insight? [Your main point here] - this has completely transformed how I approach [relevant topic].

Here's what I learned:
✅ [Key learning 1]
✅ [Key learning 2] 
✅ [Key learning 3]

The most surprising part? [Unexpected insight or result]

This experience reminded me that [broader lesson or reflection].

What's your experience with [relevant topic]? I'd love to hear your thoughts in the comments below!

#ProfessionalGrowth #IndustryInsights #Networking #CareerDevelopment

---
*Generated by Pammi AI - Your LinkedIn content creation assistant*`;

      setGeneratedContent(generatedText);
      setSuccess('Content generated successfully!');
    } catch (err) {
      setError('Failed to generate content. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleTemplateSelect = (template) => {
    setSelectedTemplate(template);
    setPrompt(template.prompt);
    setShowPreview(false);
  };

  const handleCopyContent = () => {
    navigator.clipboard.writeText(generatedContent);
    setSuccess('Content copied to clipboard!');
  };

  const handleSchedule = () => {
    // Navigate to scheduling page or open scheduling modal
    navigate('/scheduled-posts');
  };

  return (
    <Box sx={{ backgroundColor: '#000000', color: 'white', minHeight: '100vh', pt: 8 }}>
      <Container maxWidth="lg">
        {/* Header Section */}
        <Box sx={{ textAlign: 'center', mb: 8 }}>
          <Typography
            variant="h2"
            sx={{
              fontSize: { xs: '2.5rem', md: '3.5rem' },
              fontWeight: 800,
              mb: 3,
              background: 'linear-gradient(135deg, #ffffff 0%, #0077B5 100%)',
              backgroundClip: 'text',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
            }}
          >
            AI Content Generation
          </Typography>
          <Typography
            variant="h5"
            sx={{
              color: 'rgba(255, 255, 255, 0.8)',
              maxWidth: 800,
              mx: 'auto',
              mb: 4,
            }}
          >
            Transform your ideas into engaging LinkedIn posts with the power of AI. 
            Choose a template or write your own prompt to get started.
          </Typography>
        </Box>

        {/* Features Section */}
        <Box sx={{ mb: 8 }}>
          <Grid container spacing={4}>
            {features.map((feature, index) => (
              <Grid item xs={12} md={6} lg={3} key={index}>
                <Card
                  sx={{
                    backgroundColor: 'rgba(255, 255, 255, 0.05)',
                    backdropFilter: 'blur(10px)',
                    border: '1px solid rgba(255, 255, 255, 0.1)',
                    borderRadius: 3,
                    height: '100%',
                    p: 3,
                    textAlign: 'center',
                    transition: 'all 0.3s ease',
                    '&:hover': {
                      transform: 'translateY(-5px)',
                      borderColor: '#0077B5',
                      boxShadow: '0 10px 30px rgba(0, 119, 181, 0.2)',
                    },
                  }}
                >
                  <Box sx={{ mb: 2 }}>
                    {feature.icon}
                  </Box>
                  <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: 'white' }}>
                    {feature.title}
                  </Typography>
                  <Typography variant="body2" sx={{ color: 'rgba(255, 255, 255, 0.7)' }}>
                    {feature.description}
                  </Typography>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Box>

        <Grid container spacing={6}>
          {/* Left Column - Templates */}
          <Grid item xs={12} lg={4}>
            <Paper
              sx={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                backdropFilter: 'blur(10px)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                borderRadius: 3,
                p: 3,
                height: 'fit-content',
              }}
            >
              <Typography variant="h5" sx={{ fontWeight: 700, mb: 3, color: 'white' }}>
                Content Templates
              </Typography>
              <Typography variant="body2" sx={{ color: 'rgba(255, 255, 255, 0.7)', mb: 3 }}>
                Choose from our professionally crafted templates to get started quickly.
              </Typography>
              
              <Stack spacing={2}>
                {templates.map((template) => (
                  <Card
                    key={template.id}
                    sx={{
                      backgroundColor: selectedTemplate?.id === template.id 
                        ? 'rgba(0, 119, 181, 0.2)' 
                        : 'rgba(255, 255, 255, 0.05)',
                      border: selectedTemplate?.id === template.id 
                        ? '2px solid #0077B5' 
                        : '1px solid rgba(255, 255, 255, 0.1)',
                      borderRadius: 2,
                      p: 2,
                      cursor: 'pointer',
                      transition: 'all 0.3s ease',
                      '&:hover': {
                        backgroundColor: 'rgba(0, 119, 181, 0.1)',
                        borderColor: '#0077B5',
                      },
                    }}
                    onClick={() => handleTemplateSelect(template)}
                  >
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                      {template.icon}
                      <Box sx={{ flex: 1 }}>
                        <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'white', mb: 0.5 }}>
                          {template.title}
                        </Typography>
                        <Typography variant="body2" sx={{ color: 'rgba(255, 255, 255, 0.7)', fontSize: '0.85rem' }}>
                          {template.description}
                        </Typography>
                      </Box>
                    </Box>
                  </Card>
                ))}
              </Stack>
            </Paper>
          </Grid>

          {/* Right Column - Generation Interface */}
          <Grid item xs={12} lg={8}>
            <Paper
              sx={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                backdropFilter: 'blur(10px)',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                borderRadius: 3,
                p: 4,
              }}
            >
              <Typography variant="h5" sx={{ fontWeight: 700, mb: 3, color: 'white' }}>
                Generate Your Content
              </Typography>

              {error && (
                <Alert severity="error" sx={{ mb: 3 }}>
                  {error}
                </Alert>
              )}

              {success && (
                <Alert severity="success" sx={{ mb: 3 }}>
                  {success}
                </Alert>
              )}

              <TextField
                fullWidth
                multiline
                rows={4}
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe what you want to post about... (e.g., 'Share insights about remote work challenges and solutions')"
                sx={{
                  mb: 3,
                  '& .MuiOutlinedInput-root': {
                    backgroundColor: 'rgba(255, 255, 255, 0.05)',
                    '& fieldset': {
                      borderColor: 'rgba(255, 255, 255, 0.2)',
                    },
                    '&:hover fieldset': {
                      borderColor: '#0077B5',
                    },
                    '&.Mui-focused fieldset': {
                      borderColor: '#0077B5',
                    },
                  },
                  '& .MuiInputBase-input': {
                    color: 'white',
                  },
                }}
              />

              <Box sx={{ display: 'flex', gap: 2, mb: 4 }}>
                <Button
                  variant="contained"
                  size="large"
                  onClick={handleGenerate}
                  disabled={loading}
                  startIcon={loading ? <CircularProgress size={20} /> : <AutoAwesome />}
                  sx={{
                    backgroundColor: '#0077B5',
                    '&:hover': { backgroundColor: '#005885' },
                    px: 4,
                    py: 1.5,
                    fontWeight: 600,
                  }}
                >
                  {loading ? 'Generating...' : 'Generate Content'}
                </Button>

                <Button
                  variant="outlined"
                  size="large"
                  onClick={() => setPrompt('')}
                  sx={{
                    color: 'white',
                    borderColor: 'rgba(255, 255, 255, 0.3)',
                    '&:hover': {
                      borderColor: '#0077B5',
                      backgroundColor: 'rgba(0, 119, 181, 0.1)',
                    },
                  }}
                >
                  Clear
                </Button>
              </Box>

              {generatedContent && (
                <Box>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                    <Typography variant="h6" sx={{ fontWeight: 600, color: 'white' }}>
                      Generated Content
                    </Typography>
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      <Tooltip title="Copy Content">
                        <IconButton
                          onClick={handleCopyContent}
                          sx={{ color: 'rgba(255, 255, 255, 0.7)' }}
                        >
                          <ContentCopy />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Schedule Post">
                        <IconButton
                          onClick={handleSchedule}
                          sx={{ color: 'rgba(255, 255, 255, 0.7)' }}
                        >
                          <Schedule />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Regenerate">
                        <IconButton
                          onClick={handleGenerate}
                          sx={{ color: 'rgba(255, 255, 255, 0.7)' }}
                        >
                          <Refresh />
                        </IconButton>
                      </Tooltip>
                    </Box>
                  </Box>

                  <Paper
                    sx={{
                      backgroundColor: 'rgba(255, 255, 255, 0.05)',
                      border: '1px solid rgba(255, 255, 255, 0.1)',
                      borderRadius: 2,
                      p: 3,
                      mb: 3,
                    }}
                  >
                    <Typography
                      variant="body1"
                      sx={{
                        color: 'rgba(255, 255, 255, 0.9)',
                        lineHeight: 1.6,
                        whiteSpace: 'pre-wrap',
                      }}
                    >
                      {generatedContent}
                    </Typography>
                  </Paper>

                  <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
                    <Chip
                      label="AI Generated"
                      icon={<AutoAwesome />}
                      sx={{ backgroundColor: 'rgba(0, 119, 181, 0.2)', color: '#0077B5' }}
                    />
                    <Chip
                      label="Professional"
                      icon={<CheckCircle />}
                      sx={{ backgroundColor: 'rgba(40, 167, 69, 0.2)', color: '#28A745' }}
                    />
                    <Chip
                      label="Engaging"
                      icon={<TrendingUp />}
                      sx={{ backgroundColor: 'rgba(255, 193, 7, 0.2)', color: '#FFD700' }}
                    />
                  </Box>
                </Box>
              )}
            </Paper>
          </Grid>
        </Grid>

        {/* CTA Section */}
        <Box sx={{ mt: 8, textAlign: 'center' }}>
          <Paper
            sx={{
              backgroundColor: 'rgba(0, 119, 181, 0.1)',
              backdropFilter: 'blur(10px)',
              border: '1px solid rgba(0, 119, 181, 0.3)',
              borderRadius: 3,
              p: 6,
            }}
          >
            <Typography
              variant="h4"
              sx={{
                fontWeight: 700,
                mb: 2,
                background: 'linear-gradient(135deg, #ffffff 0%, #0077B5 100%)',
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              Ready to Transform Your LinkedIn?
            </Typography>
            <Typography
              variant="h6"
              sx={{ color: 'rgba(255, 255, 255, 0.8)', mb: 4, maxWidth: 600, mx: 'auto' }}
            >
              Start generating professional content that builds your personal brand and drives meaningful connections.
            </Typography>
            <Button
              variant="contained"
              size="large"
              onClick={() => navigate('/login')}
              sx={{
                backgroundColor: '#0077B5',
                color: 'white',
                px: 6,
                py: 2,
                fontSize: '1.1rem',
                fontWeight: 600,
                borderRadius: 2,
                '&:hover': {
                  backgroundColor: '#005885',
                  transform: 'translateY(-2px)',
                  boxShadow: '0 8px 25px rgba(0, 119, 181, 0.3)',
                },
                transition: 'all 0.3s ease',
              }}
            >
              Get Started Free
            </Button>
          </Paper>
        </Box>
      </Container>
    </Box>
  );
};

export default AIGeneration;
